//
//  FilmDetailInteractor.swift
//  ListarFilmesVIP
//
//  Created by William Moreira on 02/05/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

typealias FilmDetailInteractable = FilmDetailBusinessLogic & FilmDetailDataStore

protocol FilmDetailBusinessLogic {
  
  func doRequest(_ request: FilmDetailModel.Request)
}

protocol FilmDetailDataStore {
  var dataSource: FilmDetailModel.DataSource { get }
}

final class FilmDetailInteractor: FilmDetailDataStore {
  
  var dataSource: FilmDetailModel.DataSource
  
  private var presenter: FilmDetailPresentationLogic
  
  init(viewController: FilmDetailDisplayLogic?, dataSource: FilmDetailModel.DataSource) {
    self.dataSource = dataSource
    self.presenter = FilmDetailPresenter(viewController: viewController)
  }
}


// MARK: - FilmDetailBusinessLogic
extension FilmDetailInteractor: FilmDetailBusinessLogic {
  
  func doRequest(_ request: FilmDetailModel.Request) {
    DispatchQueue.global(qos: .userInitiated).async {
      
      switch request {
        
      case .doSomething(let item):
        self.doSomething(item)
      }
    }
  }
}


// MARK: - Private Zone
private extension FilmDetailInteractor {
  
  func doSomething(_ item: Int) {
    
    //construct the Service right before using it
    //let serviceX = factory.makeXService()
    
    // get new data async or sync
    //let newData = serviceX.getNewData()
    
    presenter.presentResponse(.doSomething(newItem: item + 1, isItem: true))
  }
}
