//
//  FilmDetailRouter.swift
//  ListarFilmesVIP
//
//  Created by William Moreira on 02/05/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import UIKit

protocol FilmDetailRouting {
    func routeTo(_ route: FilmDetailModel.Route)
}

protocol FilmDetailDataPassing {
    var dataStore: FilmDetailDataStore? { get set }
}

final class FilmDetailRouter:  FilmDetailDataPassing{
   
    private weak var viewController: UIViewController?
    var dataStore: FilmDetailDataStore?

    init(viewController: UIViewController?) {
        self.viewController = viewController
    }
}


// MARK: - FilmDetailRouting
extension FilmDetailRouter: FilmDetailRouting {
    
    func routeTo(_ route: FilmDetailModel.Route) {
        DispatchQueue.main.async {
            switch route {
                
            case .dismissFilmDetailScene:
                self.dismissFilmDetailScene()
                
            case .xScene(let data):
                self.showXSceneBy(data)
            }
        }
    }
}


// MARK: - Private Zone
private extension FilmDetailRouter {
    
    func dismissFilmDetailScene() {
        viewController?.dismiss(animated: true)
    }
    
    func showXSceneBy(_ data: Int) {
        print("will show the next screen")
    }
}
