//
//  FilmDetailViewController.swift
//  ListarFilmesVIP
//
//  Created by William Moreira on 02/05/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import UIKit

protocol FilmDetailDisplayLogic where Self: UIViewController {
    func displaySetupMainView(_ viewModel: FilmDetailModel.FilmDetail.ViewModel)
}

final class FilmDetailViewController: UIViewController {
    private let mainView: FilmDetailView
    private var interactor: FilmDetailInteractable!
    private var router: FilmDetailRouting!
    
    var film: Result?
    
    init(mainView: FilmDetailView, dataSource: FilmDetailModel.DataSource) {
        self.mainView = mainView
        super.init(nibName: nil, bundle: nil)
        interactor = FilmDetailInteractor(viewController: self, dataSource: dataSource)
        router = FilmDetailRouter(viewController: self)
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        mainView.backgroundColor = .white
        mainView.delegate = self

        let request = FilmDetailModel.FilmDetail.Request()
        interactor.setupMainView(request)
    }
    
    override func loadView() {
        view = mainView
    }
    
    @available(*, unavailable)
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented, You should't initialize the ViewController through Storyboards")
    }
}

// MARK: - FilmDetailDisplayLogic
extension FilmDetailViewController: FilmDetailDisplayLogic {
    func displaySetupMainView(_ viewModel: FilmDetailModel.FilmDetail.ViewModel) {
        guard let view = self.view as? FilmDetailView else { return }
        view.film  = viewModel.film
        view.updateFilm()
    }
}

// MARK: - FilmDetailViewDelegate
extension FilmDetailViewController: FilmDetailViewDelegate {
  
}

// MARK: - Private Zone
private extension FilmDetailViewController {
   
}
