//
//  FilmListInteractor.swift
//  ListarFilmesVIP
//
//  Created by William Moreira on 02/05/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

typealias FilmListInteractable = FilmListBusinessLogic & FilmListDataStore

protocol FilmListBusinessLogic {
    func configureList(_ request: FilmListModel.FilmList.Request)
}

protocol FilmListDataStore {
    var dataSource: FilmListModel.DataSource { get set }
}

final class FilmListInteractor: FilmListDataStore {
    
    var dataSource: FilmListModel.DataSource
    
    var presenter: FilmListPresentationLogic
    
    init(viewController: FilmListDisplayLogic?, dataSource: FilmListModel.DataSource) {
        self.dataSource = dataSource
        self.presenter = FilmListPresenter(viewController: viewController)
    }
}

// MARK: - FilmListBusinessLogic
extension FilmListInteractor: FilmListBusinessLogic {
    func configureList(_ request: FilmListModel.FilmList.Request) {
        let response = FilmListModel.FilmList.Response(list: dataSource.filmModelList)
        presenter.configureList(response)
    }
}
