//
//  FilmListRouter.swift
//  ListarFilmesVIP
//
//  Created by William Moreira on 02/05/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import UIKit

protocol FilmListRouting {
    func routeToFilmDetail(_ index: Int)
}

protocol FilmListDataPassing {
    var dataStore: FilmListDataStore? { get set }
}

final class FilmListRouter: FilmListDataPassing{
    
    private weak var viewController: UIViewController?
    var dataStore: FilmListDataStore?
    
    init(viewController: UIViewController?) {
        self.viewController = viewController
    }
}

// MARK: - FilmListRouting
extension FilmListRouter: FilmListRouting {
    func routeToFilmDetail(_ index: Int) {
        DispatchQueue.main.async {
            let mainView = FilmDetailView()
            guard let dataSourceFilmList = self.dataStore?.dataSource else { return }
            let film = dataSourceFilmList.filmModelList.results[index]
            let dataSourceDetail = FilmDetailModel.DataSource(film: film)
            let FilmDetailViewController = FilmDetailViewController(mainView: mainView, dataSource: dataSourceDetail)
            let backButton = UIBarButtonItem(title: ProjectStrings.back.localized, style: .plain, target: nil, action: nil)
            self.viewController?.navigationItem.backBarButtonItem = backButton
            self.viewController?.navigationController?.pushViewController(FilmDetailViewController, animated: true)
        }
    }
}
