//
//  FilmListRouter.swift
//  ListarFilmesVIP
//
//  Created by William Moreira on 02/05/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import UIKit

protocol FilmListRouting {
    
    func routeTo(_ route: FilmListModel.Route)
    
}

final class FilmListRouter {
    
    private weak var viewController: UIViewController?
    
    init(viewController: UIViewController?) {
        self.viewController = viewController
    }
}


// MARK: - FilmListRouting
extension FilmListRouter: FilmListRouting {
        
    func routeTo(_ route: FilmListModel.Route) {
        DispatchQueue.main.async {
            switch route {
                
            case .dismissFilmListScene:
                self.dismissFilmListScene()
                
            case .xScene(let data):
                self.showXSceneBy(data)
            }
        }
    }
}


// MARK: - Private Zone
private extension FilmListRouter {
    
    func dismissFilmListScene() {
        viewController?.dismiss(animated: true)
    }
    
    func showXSceneBy(_ data: Int) {
        print("will show the next screen")
    }
}
