//
//  FilmListModel.swift
//  ListarFilmesVIP
//
//  Created by William Moreira on 02/05/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//


import Foundation

enum FilmListModel {
    
    enum Request {
        case doSomething(item: Int)
    }
    
    enum Response {
        case doSomething(newItem: Int, isItem: Bool)
    }
    
    enum ViewModel {
        case doSomething(viewModelData: NSObject)
    }
    
    enum Route {
        case dismissFilmListScene
        case xScene(xData: Int)
    }
    
    struct DataSource {
        var filmModelList: FilmModel
    }
    
    enum FilmList {
        
        struct Request {
            
        }
        
        struct Response {
            var list: FilmModel
        }
        
        struct ViewModel {
            var list: FilmModel
        }
        
        struct Route {
            
        }
    }
    
    enum FilmListResult {
        struct Request {
            var result: Result
        }
        
        struct Response {
            var result: Result
            //var list: FilmModel
        }
        
        struct ViewModel {
            var result: Result
        }
        
        struct Route {
            
        }
    }
    
}
