//
//  FilmListPresenter.swift
//  ListarFilmesVIP
//
//  Created by William Moreira on 02/05/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import Foundation

protocol FilmListPresentationLogic {
    func setupMainView(_ response: FilmListModel.FilmList.Response)
}

final class FilmListPresenter {
    private weak var viewController: FilmListDisplayLogic?
    
    init(viewController: FilmListDisplayLogic?) {
        self.viewController = viewController
    }
}


// MARK: - FilmListPresentationLogic
extension FilmListPresenter: FilmListPresentationLogic {
    func setupMainView(_ response: FilmListModel.FilmList.Response) {
        let viewModel = FilmListModel.FilmList.ViewModel(list: response.list)
        viewController?.displaySetupMainView(viewModel)
    }
}


// MARK: - Private Zone
private extension FilmListPresenter {
 
}
