//
//  LoginViewController.swift
//  ListarFilmesVIP
//
//  Created by William Moreira on 02/05/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import UIKit

protocol LoginDisplayLogic where Self: UIViewController {
  
  func displayViewModel(_ viewModel: LoginModel.ViewModel)
}

final class LoginViewController: UIViewController {
  
  private let mainView: LoginView
  private var interactor: LoginInteractable!
  private var router: LoginRouting!
  
  init(mainView: LoginView, dataSource: LoginModel.DataSource) {
    self.mainView = mainView
    
    super.init(nibName: nil, bundle: nil)
    interactor = LoginInteractor(viewController: self, dataSource: dataSource)
    router = LoginRouter(viewController: self)
  }
  
  override func viewDidLoad() {
    super.viewDidLoad()
    //interactor.doSomething(item: 22)
  }
  
  override func loadView() {
    view = mainView
  }
  
  @available(*, unavailable)
  required init?(coder: NSCoder) {
    fatalError("init(coder:) has not been implemented, You should't initialize the ViewController through Storyboards")
  }
}


// MARK: - LoginDisplayLogic
extension LoginViewController: LoginDisplayLogic {
  
  func displayViewModel(_ viewModel: LoginModel.ViewModel) {
    DispatchQueue.main.async {
      switch viewModel {
        
      case .doSomething(let viewModel):
        self.displayDoSomething(viewModel)
      }
    }
  }
}


// MARK: - LoginViewDelegate
extension LoginViewController: LoginViewDelegate {
  
  func sendDataBackToParent(_ data: Data) {
    //usually this delegate takes care of users actions and requests through UI
    
    //do something with the data or message send back from mainView
  }
}


// MARK: - Private Zone
private extension LoginViewController {
  
  func displayDoSomething(_ viewModel: NSObject) {
    print("Use the mainView to present the viewModel")
    //example of using router
    router.routeTo(.xScene(xData: 22))
  }
}
