//
//  LoginInteractor.swift
//  ListarFilmesVIP
//
//  Created by William Moreira on 02/05/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

typealias LoginInteractable = LoginBusinessLogic & LoginDataStore

protocol LoginBusinessLogic {
  
  func doRequest(_ request: LoginModel.Request)
}

protocol LoginDataStore {
  var dataSource: LoginModel.DataSource { get }
}

final class LoginInteractor: LoginDataStore {
  
  var dataSource: LoginModel.DataSource
  
  private var presenter: LoginPresentationLogic
  
  init(viewController: LoginDisplayLogic?, dataSource: LoginModel.DataSource) {
    self.dataSource = dataSource
    self.presenter = LoginPresenter(viewController: viewController)
  }
}


// MARK: - LoginBusinessLogic
extension LoginInteractor: LoginBusinessLogic {
  
  func doRequest(_ request: LoginModel.Request) {
    DispatchQueue.global(qos: .userInitiated).async {
      
      switch request {
        
      case .doSomething(let item):
        self.doSomething(item)
      }
    }
  }
}


// MARK: - Private Zone
private extension LoginInteractor {
  
  func doSomething(_ item: Int) {
    
    //construct the Service right before using it
    //let serviceX = factory.makeXService()
    
    // get new data async or sync
    //let newData = serviceX.getNewData()
    
    presenter.presentResponse(.doSomething(newItem: item + 1, isItem: true))
  }
}
