//
//  CreateLoginViewController.swift
//  ListarFilmesVIP
//
//  Created by William Moreira on 02/05/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import UIKit

protocol CreateLoginDisplayLogic where Self: UIViewController {
    func displayShowAlert(_ viewModel: CreateLoginModel.CreateLogin.ViewModel)
    func displayStartLoading(_ viewModel: CreateLoginModel.CreateLogin.ViewModel)
    func displayStopLoading(_ viewModel: CreateLoginModel.CreateLogin.ViewModel)
}

final class CreateLoginViewController: BaseUIViewController {
    let mainView: CreateLoginView
    var interactor: CreateLoginInteractable!
    var router: CreateLoginRouting!
    
    init(mainView: CreateLoginView, dataSource: CreateLoginModel.DataSource) {
        self.mainView = mainView
        super.init(nibName: nil, bundle: nil)
        interactor = CreateLoginInteractor(viewController: self, dataSource: dataSource)
        router = CreateLoginRouter(viewController: self)
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        navigationItem.backBarButtonItem = UIBarButtonItem(title: "Voltar", style: .plain, target: nil, action: nil)
        mainView.backgroundColor = .white
        mainView.delegate = self
    }
    
    override func loadView() {
        view = mainView
    }
}


// MARK: - CreateLoginDisplayLogic
extension CreateLoginViewController: CreateLoginDisplayLogic {
    func displayStartLoading(_ viewModel: CreateLoginModel.CreateLogin.ViewModel) {
        self.mainView.startAnimating()
    }
    
    func displayStopLoading(_ viewModel: CreateLoginModel.CreateLogin.ViewModel) {
        self.mainView.stopAnimating()
    }
    
    func displayShowAlert(_ viewModel: CreateLoginModel.CreateLogin.ViewModel) {
        if let title = viewModel.titleMessage, let message = viewModel.message {
            mainView.showAlert(title: title, message: message) { [weak self] in
                self?.navigationController?.popViewController(animated: true)
            }
        }
    }
}

// MARK: - CreateLoginViewDelegate
extension CreateLoginViewController: CreateLoginViewDelegate {
    func createButtonPressed() {
        let request = CreateLoginModel.CreateLogin.Request(password: mainView.inputSenha.text ,login: mainView.inputLogin.text)
        interactor.doCreateLogin(request)
    }
}
