//
//  FilmDetailPresenter.swift
//  ListarFilmesVIP
//
//  Created by William Moreira on 02/05/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import Foundation

protocol FilmDetailPresentationLogic {
    func presentSetupMainView(_ response: FilmDetailModel.FilmDetail.Response)
}

final class FilmDetailPresenter {
    private weak var viewController: FilmDetailDisplayLogic?
    
    init(viewController: FilmDetailDisplayLogic?) {
        self.viewController = viewController
    }
}

// MARK: - FilmDetailPresentationLogic
extension FilmDetailPresenter: FilmDetailPresentationLogic {
    func presentSetupMainView(_ response: FilmDetailModel.FilmDetail.Response) {
        let viewModel = FilmDetailModel.FilmDetail.ViewModel(film: response.film)
        self.viewController?.displaySetupMainView(viewModel)
    }
}

// MARK: - Private Zone
private extension FilmDetailPresenter {
  
}
