//
//  LoginRouter.swift
//  ListarFilmesVIP
//
//  Created by William Moreira on 02/05/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import UIKit

protocol LoginRouting {
    func routeToCreateLogin(_ route: LoginModel.Login.Route)
    func routeToResetLogin(_ route: LoginModel.Login.Route)
    func routeToListfilms(_ route: LoginModel.Login.Route)
}

protocol LoginDataPassing {
    var dataStore: LoginDataStore? { get set }
}

final class LoginRouter: LoginDataPassing {
    private weak var viewController: UIViewController?
    var dataStore: LoginDataStore?
    
    init(viewController: UIViewController?) {
        self.viewController = viewController
    }
}

// MARK: - LoginRouting
extension LoginRouter: LoginRouting {
    func routeToCreateLogin(_ route: LoginModel.Login.Route) {
        let mainView = CreateLoginView()
        let dataSource = CreateLoginModel.DataSource()
        let createLoginViewController = CreateLoginViewController(mainView: mainView, dataSource: dataSource)
        let backButton = UIBarButtonItem(title: ProjectStrings.back.localized, style: .plain, target: nil, action: nil)
        self.viewController?.navigationItem.backBarButtonItem = backButton
        self.viewController?.navigationController?.pushViewController(createLoginViewController, animated: true)
    }
    
    func routeToResetLogin(_ route: LoginModel.Login.Route) {
        let mainView = ResetLoginView()
        let dataSource = ResetLoginModel.DataSource()
        let resetLoginViewController = ResetLoginViewController(mainView: mainView, dataSource: dataSource)
        let backButton = UIBarButtonItem(title: ProjectStrings.back.localized, style: .plain, target: nil, action: nil)
        self.viewController?.navigationItem.backBarButtonItem = backButton
        self.viewController?.navigationController?.pushViewController(resetLoginViewController, animated: true)
    }
    
    func routeToListfilms(_ route: LoginModel.Login.Route) {
        DispatchQueue.main.async {
            let mainView = FilmListView()
            guard let dataStore = self.dataStore else { return }
            let dataSource = FilmListModel.DataSource(filmModelList: dataStore.dataSource.filmModelList)
            let resetLoginViewController = FilmListViewController(mainView: mainView, dataSource: dataSource)
            let backButton = UIBarButtonItem(title: ProjectStrings.exitApp.localized, style: .plain, target: nil, action: nil)
            self.viewController?.navigationItem.backBarButtonItem = backButton
            self.viewController?.navigationController?.pushViewController(resetLoginViewController, animated: true)
        }
    }
}
