//
//  ResetLoginViewController.swift
//  ListarFilmesVIP
//
//  Created by William Moreira on 02/05/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import UIKit

protocol ResetLoginDisplayLogic where Self: UIViewController {
    func displayStartLoading(_ viewModel: ResetLoginModel.ResetLogin.Response)
    func displayStopLoading(_ viewModel: ResetLoginModel.ResetLogin.Response)
    func displayShowAlert(_ viewModel: ResetLoginModel.ResetLogin.ViewModel)
}

final class ResetLoginViewController: UIViewController {
    private let mainView: ResetLoginView
    private var interactor: ResetLoginInteractable!
    private var router: ResetLoginRouting!
    
    init(mainView: ResetLoginView, dataSource: ResetLoginModel.DataSource) {
        self.mainView = mainView
        
        super.init(nibName: nil, bundle: nil)
        interactor = ResetLoginInteractor(viewController: self, dataSource: dataSource)
        router = ResetLoginRouter(viewController: self)
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        navigationItem.backBarButtonItem = UIBarButtonItem(title: "Voltar", style: .plain, target: nil, action: nil)
        mainView.backgroundColor = .white
        mainView.delegate = self
    }
    
    override func loadView() {
        view = mainView
    }
    
    @available(*, unavailable)
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented, You should't initialize the ViewController through Storyboards")
    }
}

// MARK: - ResetLoginDisplayLogic
extension ResetLoginViewController: ResetLoginDisplayLogic {
    func displayStartLoading(_ viewModel: ResetLoginModel.ResetLogin.Response) {
        mainView.activityIndicator.startAnimating()
    }
    
    func displayStopLoading(_ viewModel: ResetLoginModel.ResetLogin.Response) {
        mainView.activityIndicator.stopAnimating()
    }
    
    func displayShowAlert(_ viewModel: ResetLoginModel.ResetLogin.ViewModel) {
        let alert = UIAlertController(title: viewModel.titleMessage, message: viewModel.message, preferredStyle: .alert)
        let okAction = UIAlertAction(title: "OK", style: .default) { action in
            if viewModel.titleMessage == "Sucesso!" {
                self.navigationController?.popViewController(animated: true)
            }
        }
        alert.addAction(okAction)
        self.present(alert, animated: true, completion: nil)
    }
}

// MARK: - ResetLoginViewDelegate
extension ResetLoginViewController: ResetLoginViewDelegate {
    func resetLoginButtonPressed() {
        let request = ResetLoginModel.ResetLogin.Request(login: mainView.inputLogin.text)
        interactor.doResetLogin(request)
    }
}

// MARK: - Private Zone
private extension ResetLoginViewController {
    
}
