//
//  ResetLoginViewController.swift
//  ListarFilmesVIP
//
//  Created by William Moreira on 02/05/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import UIKit

protocol ResetLoginDisplayLogic where Self: UIViewController {
    func displayStartLoading(_ viewModel: ResetLoginModel.ResetLogin.Response)
    func displayStopLoading(_ viewModel: ResetLoginModel.ResetLogin.Response)
    func displayShowAlert(_ viewModel: ResetLoginModel.ResetLogin.ViewModel)
}

final class ResetLoginViewController: BaseUIViewController {
    var mainView: ResetLoginView
    var interactor: ResetLoginInteractable!
    var router: ResetLoginRouting!
    
    init(mainView: ResetLoginView, dataSource: ResetLoginModel.DataSource) {
        self.mainView = mainView
        
        super.init(nibName: nil, bundle: nil)
        interactor = ResetLoginInteractor(viewController: self, dataSource: dataSource)
        router = ResetLoginRouter(viewController: self)
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        navigationItem.backBarButtonItem = UIBarButtonItem(title: "Voltar", style: .plain, target: nil, action: nil)
        mainView.backgroundColor = .white
        mainView.delegate = self
    }
    
    override func loadView() {
        view = mainView
    }
}

// MARK: - ResetLoginDisplayLogic
extension ResetLoginViewController: ResetLoginDisplayLogic {
    func displayStartLoading(_ viewModel: ResetLoginModel.ResetLogin.Response) {
        mainView.startAnimating()
    }
    
    func displayStopLoading(_ viewModel: ResetLoginModel.ResetLogin.Response) {
        mainView.stopAnimating()
    }
    
    func displayShowAlert(_ viewModel: ResetLoginModel.ResetLogin.ViewModel) {
        if let title = viewModel.titleMessage, let message = viewModel.message {
            mainView.showAlert(title: title, message: message) { [weak self] in
                self?.navigationController?.popViewController(animated: true)
            }
        }
    }
}

// MARK: - ResetLoginViewDelegate
extension ResetLoginViewController: ResetLoginViewDelegate {
    func resetLoginButtonPressed() {
        let request = ResetLoginModel.ResetLogin.Request(login: mainView.inputLogin.text)
        interactor.doResetLogin(request)
    }
}
