//
//  CreateLoginViewController.swift
//  ListarFilmesVIP
//
//  Created by William Moreira on 02/05/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import UIKit

protocol CreateLoginDisplayLogic where Self: UIViewController {
    func displayShowAlert(_ viewModel: CreateLoginModel.CreateLogin.ViewModel)
    func displayStartLoading()
    func displayStopLoading()
}

final class CreateLoginViewController: UIViewController {
    private let mainView: CreateLoginView
    private var interactor: CreateLoginInteractable!
    private var router: CreateLoginRouting!
    
    init(mainView: CreateLoginView, dataSource: CreateLoginModel.DataSource) {
        self.mainView = mainView
        super.init(nibName: nil, bundle: nil)
        interactor = CreateLoginInteractor(viewController: self, dataSource: dataSource)
        router = CreateLoginRouter(viewController: self)
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        navigationItem.backBarButtonItem = UIBarButtonItem(title: "Voltar", style: .plain, target: nil, action: nil)
        mainView.backgroundColor = .white
        mainView.delegate = self
    }
    
    override func loadView() {
        view = mainView
    }
    
    @available(*, unavailable)
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented, You should't initialize the ViewController through Storyboards")
    }
}


// MARK: - CreateLoginDisplayLogic
extension CreateLoginViewController: CreateLoginDisplayLogic {
    func displayStartLoading() {
        mainView.activityIndicator.startAnimating()
    }
    
    func displayStopLoading() {
        mainView.activityIndicator.stopAnimating()
    }
    
    func displayShowAlert(_ viewModel: CreateLoginModel.CreateLogin.ViewModel) {
        let alert = UIAlertController(title: viewModel.titleMessage, message: viewModel.message, preferredStyle: .alert)
        let okAction = UIAlertAction(title: "OK", style: .default) { action in
            if viewModel.titleMessage == "Sucesso!" {
                self.navigationController?.popViewController(animated: true)
            }
        }
        alert.addAction(okAction)
        self.present(alert, animated: true, completion: nil)
    }
}

// MARK: - CreateLoginViewDelegate
extension CreateLoginViewController: CreateLoginViewDelegate {
    func createButtonPressed() {
        let request = CreateLoginModel.CreateLogin.Request(password: mainView.inputSenha.text ,login: mainView.inputLogin.text)
        interactor.doCreateLogin(request)
    }
}

// MARK: - Private Zone
private extension CreateLoginViewController {
    
}
