//
//  ResetLoginInteractor.swift
//  ListarFilmesVIP
//
//  Created by William Moreira on 02/05/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

typealias ResetLoginInteractable = ResetLoginBusinessLogic & ResetLoginDataStore

protocol ResetLoginBusinessLogic {
  
  func doRequest(_ request: ResetLoginModel.Request)
}

protocol ResetLoginDataStore {
  var dataSource: ResetLoginModel.DataSource { get }
}

final class ResetLoginInteractor: ResetLoginDataStore {
  
  var dataSource: ResetLoginModel.DataSource
  
  private var presenter: ResetLoginPresentationLogic
  
  init(viewController: ResetLoginDisplayLogic?, dataSource: ResetLoginModel.DataSource) {
    self.dataSource = dataSource
    self.presenter = ResetLoginPresenter(viewController: viewController)
  }
}


// MARK: - ResetLoginBusinessLogic
extension ResetLoginInteractor: ResetLoginBusinessLogic {
  
  func doRequest(_ request: ResetLoginModel.Request) {
    DispatchQueue.global(qos: .userInitiated).async {
      
      switch request {
        
      case .doSomething(let item):
        self.doSomething(item)
      }
    }
  }
}


// MARK: - Private Zone
private extension ResetLoginInteractor {
  
  func doSomething(_ item: Int) {
    
    //construct the Service right before using it
    //let serviceX = factory.makeXService()
    
    // get new data async or sync
    //let newData = serviceX.getNewData()
    
    presenter.presentResponse(.doSomething(newItem: item + 1, isItem: true))
  }
}
